// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package test.grpc;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.grpc.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
