// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package test.grpc;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.grpc.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.test.grpc.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.test.grpc.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The status.
   */
  test.grpc.HealthCheckResponse.ServingStatus getStatus();
}
