// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package test.grpc;

public final class HealthProto {
  private HealthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_grpc_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_grpc_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_grpc_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_grpc_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014health.proto\022\ttest.grpc\"%\n\022HealthCheck" +
      "Request\022\017\n\007message\030\001 \001(\t\"\244\001\n\023HealthCheck" +
      "Response\022<\n\006status\030\001 \001(\0162,.test.grpc.Hea" +
      "lthCheckResponse.ServingStatus\"O\n\rServin" +
      "gStatus\022\013\n\007UNKNOWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT" +
      "_SERVING\020\002\022\023\n\017SERVICE_UNKNOWN\020\0032\305\002\n\013Heal" +
      "thCheck\022F\n\005Check\022\035.test.grpc.HealthCheck" +
      "Request\032\036.test.grpc.HealthCheckResponse\022" +
      "N\n\013WatchServer\022\035.test.grpc.HealthCheckRe" +
      "quest\032\036.test.grpc.HealthCheckResponse0\001\022" +
      "N\n\013WatchClient\022\035.test.grpc.HealthCheckRe" +
      "quest\032\036.test.grpc.HealthCheckResponse(\001\022" +
      "N\n\tWatchBidi\022\035.test.grpc.HealthCheckRequ" +
      "est\032\036.test.grpc.HealthCheckResponse(\0010\001B" +
      "\032\n\ttest.grpcB\013HealthProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_grpc_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_grpc_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_grpc_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_test_grpc_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_grpc_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_grpc_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
