// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package my.test.svc;

public final class HealthProto {
  private HealthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_test_svc_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_test_svc_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_test_svc_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_test_svc_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014health.proto\022\013my.test.svc\"%\n\022HealthChe" +
      "ckRequest\022\017\n\007message\030\001 \001(\t\"\246\001\n\023HealthChe" +
      "ckResponse\022>\n\006status\030\001 \001(\0162..my.test.svc" +
      ".HealthCheckResponse.ServingStatus\"O\n\rSe" +
      "rvingStatus\022\013\n\007UNKNOWN\020\000\022\013\n\007SERVING\020\001\022\017\n" +
      "\013NOT_SERVING\020\002\022\023\n\017SERVICE_UNKNOWN\020\0032\325\002\n\013" +
      "HealthCheck\022J\n\005Check\022\037.my.test.svc.Healt" +
      "hCheckRequest\032 .my.test.svc.HealthCheckR" +
      "esponse\022R\n\013WatchServer\022\037.my.test.svc.Hea" +
      "lthCheckRequest\032 .my.test.svc.HealthChec" +
      "kResponse0\001\022R\n\013WatchClient\022\037.my.test.svc" +
      ".HealthCheckRequest\032 .my.test.svc.Health" +
      "CheckResponse(\001\022R\n\tWatchBidi\022\037.my.test.s" +
      "vc.HealthCheckRequest\032 .my.test.svc.Heal" +
      "thCheckResponse(\0010\001B\034\n\013my.test.svcB\013Heal" +
      "thProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_my_test_svc_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_my_test_svc_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_test_svc_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_my_test_svc_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_my_test_svc_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_test_svc_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
