// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package my.test.svc;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.test.svc.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.my.test.svc.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.my.test.svc.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The status.
   */
  my.test.svc.HealthCheckResponse.ServingStatus getStatus();
}
